@JWTDemo_HostAddress = http://localhost:5157
@token = <paste-token-from-login-response>

POST {{JWTDemo_HostAddress}}/login
Content-Type: application/json

{
  "username": "demo",
  "password": "password123"
}

###

GET {{JWTDemo_HostAddress}}/secure
Accept: application/json
Authorization: Bearer {{token}}

###
